-- AJUSTAR ACORDE A LA BASE DE DATOS

INSERT INTO public."TROL"
  ("NOMBRE", "FCREACION", "FMODIFICACION", "OBSERVACION", "ESTADO", "USUARIOINGRESO", "USERMODIFICACION", "CODIGO")
VALUES
  ('ADMIN', NOW(), NULL, 'USUARIO TIENE ACCESO A TODOS LOS MODULOS', 'ACT', 'ADMIN', NULL, 'ADM'),
  ('EMPLEADO GENERAL', NOW(), NULL, NULL, 'ACT', 'ADMIN', NULL, 'EPG'),
  ('CLIENTE', NOW(), NULL, 'CLIENTE DE LA APLICACION EN GENERAL', 'ACT', 'ADMIN', NULL, 'CLT');


-- Datos ficticios de la SUCURSAL MATRIZ
INSERT INTO public."TSUCURSAL"
  ("NOMBRE", "DIRECCION", "ESTADO", "FCREACION", "FMODIFICACION", "USUARIOINGRESO", "USERMODIFICACION", "LATITUD", "LONGITUD", "CONTACTO")
VALUES
  ('MATRIZ', 'CIUDAD FICTICIA - AV. PRINCIPAL 123', TRUE, NOW(), NULL, 'ADMIN', NULL, -1.000000, -78.000000,
   '0990000000');

-- PERSONA (datos ficticios)
INSERT INTO public."TPERSONA" ("IDENTIFICACION", "NOMBRES", "APELLIDOS", "FNACIMIENTO", "GENERO",
   "CORREO", "TELEFONO", "DIRECCION", "TIPOIDENTIFICACION", "ESTADO", "FCREACION", "FMODIFICACION", "USUARIOINGRESO", "USERMODIFICACION")
VALUES
  ('0999999999',
   'USUARIO', 'PRUEBA', '1990-01-01 00:00:00', 'M', 'usuario.prueba@example.com', '0991111111',
   'CIUDAD FICTICIA', 'Cedula', 'ACT', NOW(), NULL, 'ADMIN', NULL);

-- Usuario (datos ficticios)
INSERT INTO public."TUSUARIO"
  ("IDSUCURSAL", "IDENTIFICACION", "USUARIO", "PASSWORD",
   "TEMPORAL", "FCREACION", "FMODIFICACION",
   "USUARIOINGRESO", "USERMODIFICACION")
VALUES
  (1, '0999999999',
   'admin_demo',
   '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918',
   FALSE, NOW(), NULL,
   'ADMIN', NULL);

-- ROL - USUARIO (datos ficticios)
INSERT INTO public."TROLUSUARIO"
  ("IDUSUARIO", "IDROL", "FCREACION", "FMODIFICACION",
   "USUARIOINGRESO", "USERMODIFICACION", "ESTADO")
VALUES
  (1, 1, NOW(), NULL,
   'ADMIN', NULL, 'ACT');