// ignore_for_file: constant_identifier_names
//ENTIDADES DE LA APLICACION CENTRALIZADOS
enum Entities {
  TDETALLEVENTA("TDETALLEVENTA"),
  TDIRECCION_CLIENTE("TDIRECCION_CLIENTE"),
  TDISPOSITIVO("TDISPOSITIVO"),
  TENTREGA("TENTREGA"),
  TFACTURA("TFACTURA"),
  TINGRESO_EGRESO("TINGRESO_EGRESO"),
  TINVENTARIO("TINVENTARIO"),
  TMESA("TMESA"),
  TPERSONA("TPERSONA"),
  TPLANILLA("TPLANILLA"),
  TPRODUCTO("TPRODUCTO"),
  TPRODUCTO_INSUMO("TPRODUCTO_INSUMO"),
  TROL("TROL"),
  TROLUSUARIO("TROLUSUARIO"),
  TSESION("TSESION"),
  TSUCURSAL("TSUCURSAL"),
  TUSUARIO("TUSUARIO"),
  TVENTA("TVENTA");

  final String tableName;
  const Entities(this.tableName);
}
